import type { Metadata } from 'next'
import { ReduxProvider } from '@/redux/provider'
import './globals.scss'
//===========================================================================================================

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<ReduxProvider>
			<html lang="en">
				<body>{children}</body>
			</html>
		</ReduxProvider>
	)
}
